name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: php-actions/composer@v6 # or alternative dependency management
      with:
        php_version: "7.4"
    - uses: php-actions/phpunit@v3
      with:
        php_version: "7.4"
        version: "8"
        configuration: "phpunit.xml"
    # ... then your own project steps ...
